### ISSUE TITLE
Potential label leakage

### ISSUE THREAD

**Issue by siqim** [storyandwine/GEARSage-DGraphFin#2]
Hi,

Thanks for your code! With a quick glance at the code, it seems to me [add_feature_flag ](https://github.com/storyandwine/GEARSage-DGraphFin/blob/bdbc8b4a0ed5e61f1829055fabf46c571151f6c3/feat_func.py#L24) and [add_label_counts](https://github.com/storyandwine/GEARSage-DGraphFin/blob/bdbc8b4a0ed5e61f1829055fabf46c571151f6c3/feat_func.py#L32) may implicitly leak info of test labels into features as essentially test labels are also used to augment node features for training. Did I miss anything? And how would the performance change if these features are removed?

Best,
Siqi

**Comment by storyandwine** [comment]
Hi,
Thank you very much for noticing this project and opening the good issue!
In short, there is no leakage. I'll analyze the reasons one by one for your reference. 
1. To review the label definitions in the dataset, 0 represents a normal node, 1 represents a fraud node, and 2 and 3 represent background nodes.
2. The add_label_counts function only uses the information of the foreground node (0 or 1) and the background node (2 or 3), so there is no label leakage problem, because no matter whether the node is a normal node or a fraud node, the processing procedure is the same in this function.
3. Perhaps the most confusing thing for you is this function add_feature_flag, which your text was add_feature_flag while link is the function called add_label_feature. Here, we'll discuss both.
4. As for add_feature_flag, this function wants to capture the presence or absence of node features. Because it is only a feature engineering, so has nothing to do with the label leakage.
5. The idea of the add_label_feature function to propagate labels along with features has also been widely discussed, a typical example being [UniMP](https://arxiv.org/pdf/2009.03509.pdf). Specifically, we use y[y == 1] = 0 at the beginning of the function to avoid directly exploiting the tag information that needs to be predicted, thus avoiding leakage. All fraudulent nodes are temporarily considered as normal users to simulate the scenario of mining fraudulent users from normal users.
6. Thanks for your suggestion of ablation experiment. After removing the add_label_feature function, we conducted a new experiment, and the experimental results are as follows:
![3705316cccd3320fe2dfcf1633224df](https://user-images.githubusercontent.com/27343352/212585155-d0af30fb-cf8c-4de2-ad6c-f94e0c46f26d.jpg)
![f76cc915559f3e415bbbb40257e898c](https://user-images.githubusercontent.com/27343352/212585186-1f72f4ff-0f46-4e1c-99ab-cc8901255686.png)
Almost no effect compared to before removal.

If you have any ideas, feel free to continue to contact me, by the way, wish you 2023 a happy New Year, a happy Spring Festival !

Best wishes!

**Comment by siqim** [comment]
Thank you for your reply and happy new year! 

Sorry, I meant to say `add_label_feature` and `add_label_counts`, but I copied a wrong function name. 

I still have three follow-up questions:

1. For `add_label_feature`, I can see it will not leak the info of class `1`, will it leak other classes' info? I thought the leaderboard of DGraphFin would evaluate all four classes.
2. Could you further clarify how `add_label_counts` would not leak label info? Please correct me if I am wrong: after using `add_label_counts`, each node would roughly know how many of its neighbors are `background_nodes`  during training, and thus how many are `foreground_nodes`, but some of those `foreground_nodes` may be test nodes, and their info essentially will be leaked?
3. How would the model perform if one removes `add_label_counts`? Or even removes both `add_label_feature` and `add_label_counts`?

I guess the thing that confuses me the most is the problem formulation. Is it actually evaluating binary classification performance and it only cares about class `0` and `1`? But in a real test setting, will one really have or be allowed to use the label of class `2` and `3`?

Thanks again for your reply!

**Comment by siqim** [comment]
After some checking, I guess what I was referring to is the leakage of class label `2` and `3`. If they're allowed to be used, then I think the two functions are totally fine. So my questions are then actually one question: are we allowed to directly use class label `2` and `3`?

**Comment by storyandwine** [comment]
Using background label is OK.
and the split of dataset only consider  0 and 1.
One possible interpretation is that the foreground nodes indicate customers with lending behavior and the background nodes indicate customers with no lending behavior at the moment.

**Comment by siqim** [comment]
That makes sense. Thank you!
